"""
handlers/code_runner.py — F8: Code interpreter with self-correction loop.

Executes Python code generated by the LLM in a subprocess, captures
output, and feeds errors back to the LLM for self-correction (up to
max_retries times).

Usage (internal):
    from .code_runner import run_generated_code
    await run_generated_code(code, pipeline, original_prompt, model, max_retries=3,
                             language="python", timeout=30)

Supported languages: python, bash, node, ruby
"""
import asyncio
import subprocess
import sys
import textwrap

from ..printer import print_error, print_info, print_success, print_warning

# ── Language runners ──────────────────────────────────────────────────────────

RUNNERS: dict[str, list[str]] = {
    "python": [sys.executable, "-c"],
    "bash":   ["bash",         "-c"],
    "node":   ["node",         "-e"],
    "ruby":   ["ruby",         "-e"],
}

_DEFAULT_TIMEOUT = 30


def _print_code(code: str, label: str = "Code:") -> None:
    """Pretty-print code with rich syntax highlighting, falling back to plain."""
    print()
    try:
        from rich.console import Console
        from rich.syntax import Syntax
        console = Console()
        console.print(Syntax(code, "python", theme="monokai", line_numbers=False, padding=(0, 1)))
    except ImportError:
        for line in code.splitlines():
            print(f"  {line}")
    print()


_CORRECTION_SYSTEM = """You are a Python code correction assistant.

You will be given a Python script that failed with an error.
Return ONLY the corrected Python code — no explanation, no markdown fences, no backticks.
Output raw Python only. The code must be complete and runnable as-is.
"""

def _extract_code(text: str) -> str:
    """Strip markdown fences from LLM output to get raw Python."""
    text = text.strip()
    # Strip ```python ... ``` or ``` ... ```
    if text.startswith("```"):
        lines = text.splitlines()
        # Remove first line (```python or ```) and last line (```)
        inner = lines[1:] if lines[0].startswith("```") else lines
        if inner and inner[-1].strip() == "```":
            inner = inner[:-1]
        return "\n".join(inner).strip()
    return text


def _run_code(code: str, language: str = "python", timeout: int = _DEFAULT_TIMEOUT) -> tuple[int, str, str]:
    """Run code in a subprocess for the given language. Returns (exit_code, stdout, stderr)."""
    runner = RUNNERS.get(language, RUNNERS["python"])
    try:
        result = subprocess.run(
            runner + [code],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return 1, "", f"Timeout: code took longer than {timeout}s"
    except FileNotFoundError:
        return 1, "", f"Runtime not found: '{runner[0]}' — is {language} installed?"
    except Exception as e:
        return 1, "", str(e)


async def run_generated_code(
    code: str,
    pipeline,
    original_prompt: str,
    model: str | None = None,
    max_retries: int = 3,
    show_code: bool = True,
    language: str = "python",
    timeout: int = _DEFAULT_TIMEOUT,
) -> None:
    """
    Execute code, self-correct on errors, stream final output live.

    Args:
        code:            The code string to run (may have ``` fences).
        pipeline:        ProviderPipeline instance for correction calls.
        original_prompt: The original user prompt (used in correction context).
        model:           Optional model override for correction calls.
        max_retries:     Max self-correction attempts (default: 3).
        show_code:       Print the code before running (default: True).
        language:        Runtime to use — python, bash, node, ruby (default: python).
        timeout:         Subprocess timeout in seconds (default: 30).
    """
    from ..providers.pipeline import ProviderExhaustedError

    code = _extract_code(code)
    lang_label = f" [{language}]" if language != "python" else ""

    for attempt in range(max_retries + 1):
        if show_code or attempt > 0:
            label = f"Code{lang_label}:" if attempt == 0 else f"Corrected code (attempt {attempt}):"
            _print_code(code, label)

        print_info("Running..." if attempt == 0 else f"Retrying ({attempt}/{max_retries})...")

        # ── Stream stdout live using asyncio subprocess ───────────────────────
        runner = RUNNERS.get(language, RUNNERS["python"])
        try:
            async def _run_and_stream() -> tuple[int, str]:
                proc = await asyncio.create_subprocess_exec(
                    *runner, code,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                )
                assert proc.stdout is not None
                async for raw_line in proc.stdout:
                    line = raw_line.decode(errors="replace")
                    print(line, end="", flush=True)
                stdout_out, stderr_bytes = await proc.communicate()
                stderr = stderr_bytes.decode(errors="replace") if stderr_bytes else ""
                return proc.returncode or 0, stderr

            exit_code, stderr = await asyncio.wait_for(_run_and_stream(), timeout=timeout)
        except asyncio.TimeoutError:
            exit_code, stderr = 1, f"Timeout: code took longer than {timeout}s"
        except FileNotFoundError:
            exit_code, stderr = 1, f"Runtime not found: '{runner[0]}' — is {language} installed?"
        except Exception as e:
            exit_code, stderr = 1, str(e)

        if exit_code == 0:
            correction_note = f" ({attempt} correction(s))" if attempt > 0 else ""
            print_success(f"Done.{correction_note}")
            return

        # Failed — show error
        print_warning(f"Error (exit {exit_code}):")
        if stderr.strip():
            print(f"\033[31m{stderr.strip()}\033[0m")

        if attempt >= max_retries:
            print_error(f"Failed after {max_retries} correction attempt(s). Giving up.")
            return

        # Ask LLM to fix it
        print_info(f"Asking AI to correct... ({attempt + 1}/{max_retries})")
        correction_messages = [
            {"role": "system", "content": _CORRECTION_SYSTEM},
            {"role": "user", "content": (
                f"Original task: {original_prompt}\n\n"
                f"Code that failed:\n```{language}\n{code}\n```\n\n"
                f"Error output:\n{stderr.strip()[:1500]}\n\n"
                f"Return only the corrected {language} code."
            )},
        ]

        try:
            chunks = []
            async for chunk in pipeline.stream(correction_messages, model=model, requires_vision=False):
                chunks.append(chunk)
            corrected = _extract_code("".join(chunks).strip())
            if not corrected:
                print_error("AI returned empty correction. Stopping.")
                return
            code = corrected
        except ProviderExhaustedError:
            print_error("All providers exhausted during correction. Stopping.")
            return
