"""
handlers/code_runner.py — F8: Code interpreter with self-correction loop.

Executes Python code generated by the LLM in a subprocess, captures
output, and feeds errors back to the LLM for self-correction (up to
max_retries times).

Usage (internal):
    from .code_runner import run_generated_code
    await run_generated_code(code, pipeline, original_prompt, model, max_retries=3)
"""
import subprocess
import sys
import textwrap

from ..printer import print_error, print_info, print_success, print_warning


def _print_code(code: str, label: str = "Code:") -> None:
    """Pretty-print code with rich syntax highlighting, falling back to plain."""
    print()
    try:
        from rich.console import Console
        from rich.syntax import Syntax
        console = Console()
        console.print(Syntax(code, "python", theme="monokai", line_numbers=False, padding=(0, 1)))
    except ImportError:
        for line in code.splitlines():
            print(f"  {line}")
    print()


_CORRECTION_SYSTEM = """You are a Python code correction assistant.

You will be given a Python script that failed with an error.
Return ONLY the corrected Python code — no explanation, no markdown fences, no backticks.
Output raw Python only. The code must be complete and runnable as-is.
"""

_TIMEOUT_SECONDS = 30


def _extract_code(text: str) -> str:
    """Strip markdown fences from LLM output to get raw Python."""
    text = text.strip()
    # Strip ```python ... ``` or ``` ... ```
    if text.startswith("```"):
        lines = text.splitlines()
        # Remove first line (```python or ```) and last line (```)
        inner = lines[1:] if lines[0].startswith("```") else lines
        if inner and inner[-1].strip() == "```":
            inner = inner[:-1]
        return "\n".join(inner).strip()
    return text


def _run_code(code: str) -> tuple[int, str, str]:
    """Run Python code in a subprocess. Returns (exit_code, stdout, stderr)."""
    try:
        result = subprocess.run(
            [sys.executable, "-c", code],
            capture_output=True,
            text=True,
            timeout=_TIMEOUT_SECONDS,
        )
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        return 1, "", f"Timeout: code took longer than {_TIMEOUT_SECONDS}s"
    except Exception as e:
        return 1, "", str(e)


async def run_generated_code(
    code: str,
    pipeline,
    original_prompt: str,
    model: str | None = None,
    max_retries: int = 3,
    show_code: bool = True,
) -> None:
    """
    Execute Python code, self-correct on errors, print final output.

    Args:
        code:            The Python code string to run (may have ``` fences).
        pipeline:        ProviderPipeline instance for correction calls.
        original_prompt: The original user prompt (used in correction context).
        model:           Optional model override for correction calls.
        max_retries:     Max self-correction attempts (default: 3).
        show_code:       Print the code before running (default: True).
    """
    from ..providers.pipeline import ProviderExhaustedError

    code = _extract_code(code)

    for attempt in range(max_retries + 1):
        if show_code or attempt > 0:
            label = "Code:" if attempt == 0 else f"Corrected code (attempt {attempt}):"
            _print_code(code, label)

        print_info("Running..." if attempt == 0 else f"Retrying ({attempt}/{max_retries})...")
        exit_code, stdout, stderr = _run_code(code)

        if exit_code == 0:
            if stdout.strip():
                print(stdout.rstrip())
            print_success(f"Done.{' (' + str(attempt) + ' correction(s))' if attempt > 0 else ''}")
            return

        # Failed — show error
        print_warning(f"Error (exit {exit_code}):")
        if stderr.strip():
            print(f"\033[31m{stderr.strip()}\033[0m")

        if attempt >= max_retries:
            print_error(f"Failed after {max_retries} correction attempt(s). Giving up.")
            return

        # Ask LLM to fix it
        print_info(f"Asking AI to correct... ({attempt + 1}/{max_retries})")
        correction_messages = [
            {"role": "system", "content": _CORRECTION_SYSTEM},
            {"role": "user", "content": (
                f"Original task: {original_prompt}\n\n"
                f"Code that failed:\n```python\n{code}\n```\n\n"
                f"Error output:\n{stderr.strip()[:1500]}\n\n"
                f"Return only the corrected Python code."
            )},
        ]

        try:
            chunks = []
            async for chunk in pipeline.stream(correction_messages, model=model, requires_vision=False):
                chunks.append(chunk)
            corrected = _extract_code("".join(chunks).strip())
            if not corrected:
                print_error("AI returned empty correction. Stopping.")
                return
            code = corrected
        except ProviderExhaustedError:
            print_error("All providers exhausted during correction. Stopping.")
            return
